version: '3.1'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=elastic"
      - "xpack.security.enabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      - "ELASTICSEARCH_URL=http://localhost:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=elastic"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  EklKibanaExampleWebApi:
    container_name: EklKibanaExampleWebApi
    build:
      context: ./EklKibanaExampleWebApi # Specify the path to your ASP.NET Core app
      dockerfile: ./Dockerfile   

    image: eklkibanaexamplewebapi   
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "6060:80"
      - "6061:443"
    